// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterQualityMonitoring.Models;

#nullable disable

namespace WaterQualityMonitoring.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WaterQualityMonitoring.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "admin@waterquality.ps",
                            Governorate = "Gaza",
                            Password = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            PhoneNumber = "0599000000",
                            RegistrationDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "ahmad@gmail.com",
                            Governorate = "Rafah",
                            Password = "306098fa01257f8e4809cbdfca258d8c22c7fb12937cc2616ef06aa20fd8008e",
                            PhoneNumber = "0599111111",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "ahmad"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "sara@hotmail.com",
                            Governorate = "KhanYounis",
                            Password = "926b4b8a00cfab44b758450fa6bf188d4bf8541c2fd6b3d9b93d152d43a99f64",
                            PhoneNumber = "0599222222",
                            RegistrationDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "sara"
                        });
                });

            modelBuilder.Entity("WaterQualityMonitoring.Models.WaterReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PollutionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("UserID");

                    b.ToTable("WaterReports");

                    b.HasData(
                        new
                        {
                            ReportID = 1,
                            Description = "Unpleasant odor and strange color in drinking water",
                            Location = "Shuja'iyya neighborhood - Gaza",
                            PollutionType = "chemical pollution",
                            ReportDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SourceType = "sewage from settlements",
                            Status = "Confirmed",
                            UserID = 2
                        },
                        new
                        {
                            ReportID = 2,
                            Description = "Bacterial contamination led to intestinal diseases",
                            Location = "Nuseirat camp",
                            PollutionType = "bacteria",
                            ReportDate = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SourceType = "sewage leak",
                            Status = "Pending",
                            UserID = 3
                        },
                        new
                        {
                            ReportID = 3,
                            Description = "Salty water unfit for drinking",
                            Location = "Rafah City - Brazil Neighborhood",
                            PollutionType = "high salinity",
                            ReportDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SourceType = "Seawater intrusion",
                            Status = "Confirmed",
                            UserID = 1
                        },
                        new
                        {
                            ReportID = 4,
                            Description = "Complaints of stomach pain after drinking water",
                            Location = "Al-Tuffah neighborhood - Gaza",
                            PollutionType = "heavy metals",
                            ReportDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SourceType = "industrial waste",
                            Status = "Pending",
                            UserID = 2
                        },
                        new
                        {
                            ReportID = 5,
                            Description = "Turbid water with sediment present",
                            Location = "Jabalia camp",
                            PollutionType = "High turbidity",
                            ReportDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SourceType = "Construction and excavation works",
                            Status = "Confirmed",
                            UserID = 3
                        });
                });

            modelBuilder.Entity("WaterQualityMonitoring.Models.WaterReport", b =>
                {
                    b.HasOne("WaterQualityMonitoring.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
